### ISSUE TITLE
[Translation] Russian language

### ISSUE THREAD

**Issue by DearFox** [spiralhalo/McHud#1]
Adapted Russian translation.

[ru_ru.zip](https://github.com/spiralhalo/McHud/files/8677449/ru_ru.zip)
_(requires testing)_

**Comment by spiralhalo** [comment]
Seems fine. Can you make a PR so you get credited properly in the repo?

If you don't use git, you can go to https://github.com/spiralhalo/McHud/tree/master/src/main/resources/assets/sh_mchud/lang and click `Add file` > `Create file` at top right corner and follow the instructions.

**Comment by DearFox** [comment]
I hope I did everything right
https://github.com/spiralhalo/McHud/pull/4

**Comment by spiralhalo** [comment]
Closed with https://github.com/spiralhalo/McHud/commit/704dab441881c95665b82f8644cffcb65e1699fe
